Repository aditya109/Bank-Reconcilation-Statement-Validator, pull requests merged in 2020-04, with the labels that each got.

#20 Refactoring the frontend ReactJS
  1.1/assets/4719318-computer-icons-piggy-bank-money-saving-png-clipart-bank-cheque-saving-png-728_508_preview.png
  1.1/assets/bank-account-icon-66.png
  1.1/assets/design-ui/ui.jpg
  1.1/assets/try.jpg
  1.1/controller/__pycache__/driver.cpython-37.pyc
  1.1/main.py
  1.1/trials/a.txt
  1.1/trials/b.txt
  1.1/trials/test.py
  1.1/utils/__pycache__/classLoader.cpython-37.pyc
  1.1/utils/__pycache__/helpers.cpython-37.pyc
  1.1/utils/classLoader.py
  1.1/utils/helpers.py
  1.1/windows/__pycache__/dfloader.cpython-37.pyc
  1.1/windows/__pycache__/home.cpython-37.pyc
  1.1/windows/__pycache__/matchoptions.cpython-37.pyc
  1.1/windows/__pycache__/nav.cpython-37.pyc
  1.1/windows/__pycache__/report.cpython-37.pyc
  1.1/windows/__pycache__/search.cpython-37.pyc
  1.1/windows/__pycache__/tutorial.cpython-37.pyc
  1.1/windows/__pycache__/warning.cpython-37.pyc
  1.1/windows/dfloader.py
  1.1/windows/home.py
  1.2/design-ui/fonts.docx
  1.2/design-ui/report-template.txt
  1.2/design-ui/ui.jpg
  1.2/server/main.py
  1.2/ui/.gitignore
  1.2/ui/README.md
  1.2/ui/package-lock.json
  1.2/ui/package.json
  1.2/ui/public/favicon.ico
  1.2/ui/public/index.html
  1.2/ui/public/manifest.json
  1.2/ui/public/robots.txt
  1.2/ui/src/App.css
  1.2/ui/src/App.js
  1.2/ui/src/App.test.js
  1.2/ui/src/components/DFLoadingPage.js
  1.2/ui/src/components/HomePage.js
  1.2/ui/src/components/NavPage.js
  1.2/ui/src/components/PageOptions.js
  1.2/ui/src/components/ReportPage.js
  1.2/ui/src/components/SearchingPage.js
  1.2/ui/src/components/TutorialPage.js
  1.2/ui/src/components/WarningPage.js
  1.2/ui/src/index.css
  1.2/ui/src/index.js
  1.2/ui/src/serviceWorker.js
  1.2/ui/src/setupTests.js
  1.2/ui/src/styles/homepage.css
  1.2/ui/src/styles/navpage.css
Labels: frontend, refactor, ui

#21 (basic-ui): made basic React Framework and complete ui prototypes
  1.2/design-ui/font-color-hex.txt
  1.2/design-ui/main-window-ui/Screenshot (60).png
  1.2/design-ui/main-window-ui/Screenshot (61).png
  1.2/design-ui/main-window-ui/Screenshot (62).png
  1.2/design-ui/main-window-ui/Screenshot (63).png
  1.2/design-ui/main-window-ui/Screenshot (64).png
  1.2/design-ui/main-window-ui/Screenshot (65).png
  1.2/ui/package-lock.json
  1.2/ui/package.json
  1.2/ui/public/img/database-storage.svg
  1.2/ui/public/img/df.svg
  1.2/ui/public/img/graph.svg
  1.2/ui/public/img/left-arrow.svg
  1.2/ui/public/img/plus.svg
  1.2/ui/public/img/report.svg
  1.2/ui/public/img/right-arrow.svg
  1.2/ui/src/components/DFLoadingPage.js
  1.2/ui/src/components/PageOptions.js
  1.2/ui/src/components/ReportPage.js
  1.2/ui/src/components/SearchingPage.js
  1.2/ui/src/components/TutorialPage.js
  1.2/ui/src/components/WarningPage.js
  1.2/ui/src/index.css
  1.2/ui/src/styles/dfloadingpage.css
  1.2/ui/src/styles/homepage.css
  1.2/ui/src/styles/pageoptions.css
  1.2/ui/src/styles/reportpage.css
  1.2/ui/src/styles/searchingpage.css
  1.2/ui/src/styles/tutorialpage.css
  1.2/ui/src/styles/warningpage.css
  README.md
Labels: frontend, scratch-code, ui

#28 Starting control components
  1.2/ui/public/img/graph.svg
  1.2/ui/src/App.js
  1.2/ui/src/components/ControlPage.js
  1.2/ui/src/components/DFLoadingPage.js
  1.2/ui/src/components/NavPage.js
  1.2/ui/src/components/PageOptions.js
  1.2/ui/src/components/TutorialPage.js
  1.2/ui/src/index.css
  1.2/ui/src/styles/controlpage.css
  1.2/ui/src/styles/dfloadingpage.css
  1.2/ui/src/styles/navpage.css
  1.2/ui/src/styles/pageoptions.css
Labels: WIP, frontend, scratch-code, ui

#29 added warning component
  1.2/ui/src/components/WarningPage.js
  1.2/ui/src/styles/warningpage.css
Labels: frontend, scratch-code, ui

#36 Built a server that has three routes and displays the input given.
  1.2/server/main.py
Labels: WIP, backend, core, scratch-code

#38 WIP Added Backend Design Document
  1.2/server/.idea/.gitignore
  1.2/server/.idea/inspectionProfiles/profiles_settings.xml
  1.2/server/.idea/misc.xml
  1.2/server/.idea/modules.xml
  1.2/server/.idea/server.iml
  1.2/server/.idea/vcs.xml
  1.2/server/controller/__init__.py
  1.2/server/controller/__pycache__/__init__.cpython-38.pyc
  1.2/server/controller/__pycache__/cont.cpython-38.pyc
  1.2/server/controller/cont.py
  1.2/server/domain/__init__.py
  1.2/server/domain/domain.py
  1.2/server/handlers/__init__.py
  1.2/server/main.py
  1.2/server/pkg/__init__.py
  1.2/server/planning.md
  1.2/server/requirements.txt
  1.2/server/services/__init__.py
  1.2/ui/src/components/DFLoadingPage.js
Labels: WIP, backend, core, docs
